import { GridFooterPositions } from './types/grid-footer-positions';
import { AfterViewInit, ChangeDetectorRef, ComponentFactoryResolver, EventEmitter, OnChanges, OnInit, ViewContainerRef } from '@angular/core';
import { FormioAlerts } from 'angular-formio';
import { GridHeaderComponent } from './GridHeaderComponent';
import { GridBodyComponent } from './GridBodyComponent';
import { GridFooterComponent } from './GridFooterComponent';
import { FormioPromiseService } from 'angular-formio';
import { GridColumn } from './types/grid-column';
import { GridHeader } from './types/grid-header';
import * as i0 from "@angular/core";
export declare class FormioGridComponent implements OnChanges, OnInit, AfterViewInit {
    alerts: FormioAlerts;
    private resolver;
    private ref;
    footerPosition: GridFooterPositions;
    src?: string;
    items?: Array<any>;
    onForm?: Promise<any>;
    query?: any;
    refresh?: EventEmitter<object>;
    columns?: Array<GridColumn>;
    gridType?: string;
    size?: number;
    components?: any;
    formio?: FormioPromiseService;
    createText: String;
    isActionAllowed: any;
    select: EventEmitter<object>;
    rowSelect: EventEmitter<object>;
    rowAction: EventEmitter<object>;
    createItem: EventEmitter<any>;
    error: EventEmitter<any>;
    headerElement: ViewContainerRef;
    bodyElement: ViewContainerRef;
    footerElement: ViewContainerRef;
    page: number;
    isLoading: boolean;
    initialized: boolean;
    header: GridHeaderComponent;
    body: GridBodyComponent;
    footer: GridFooterComponent;
    footerPositions: typeof GridFooterPositions;
    constructor(alerts: FormioAlerts, resolver: ComponentFactoryResolver, ref: ChangeDetectorRef);
    createComponent(property: any, component: any): any;
    loadGrid(src?: string): void;
    ngOnInit(): void;
    ngOnChanges(changes: any): void;
    ngAfterViewInit(): void;
    actionAllowed(action: any): any;
    onError(error: any): void;
    refreshGrid(query?: any): any;
    setPage(num?: number): void;
    sortColumn(header: GridHeader): void;
    pageChanged(page: any): void;
    static ɵfac: i0.ɵɵFactoryDef<FormioGridComponent, never>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<FormioGridComponent, "formio-grid", never, { "footerPosition": "footerPosition"; "src": "src"; "items": "items"; "onForm": "onForm"; "query": "query"; "refresh": "refresh"; "columns": "columns"; "gridType": "gridType"; "size": "size"; "components": "components"; "formio": "formio"; "createText": "createText"; "isActionAllowed": "isActionAllowed"; }, { "select": "select"; "rowSelect": "rowSelect"; "rowAction": "rowAction"; "createItem": "createItem"; "error": "error"; }, never, never>;
}
//# sourceMappingURL=grid.component.d.ts.map