import { ApplicationRef, EventEmitter } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { FormioResourceConfig } from './resource.config';
import { FormioResources } from './resources.service';
import { FormioPromiseService } from 'angular-formio';
import { FormioAlerts } from 'angular-formio';
import { FormioAppConfig } from 'angular-formio';
import { FormioRefreshValue } from 'angular-formio';
import Promise from 'native-promise-only';
import * as i0 from "@angular/core";
export declare class FormioResourceService {
    appConfig: FormioAppConfig;
    config: FormioResourceConfig;
    resourcesService: FormioResources;
    appRef: ApplicationRef;
    initialized: boolean;
    form: any;
    alerts: FormioAlerts;
    resource: any;
    resourceUrl?: string;
    formUrl: string;
    formFormio: FormioPromiseService;
    formio: FormioPromiseService;
    refresh: EventEmitter<FormioRefreshValue>;
    resourceLoading?: Promise<any>;
    resourceLoaded?: Promise<any>;
    resourceId?: string;
    resources: any;
    formLoading?: Promise<any>;
    formLoaded: Promise<any>;
    formResolve: any;
    formReject: any;
    isLoading: boolean;
    constructor(appConfig: FormioAppConfig, config: FormioResourceConfig, resourcesService: FormioResources, appRef: ApplicationRef);
    initialize(): void;
    init(): any;
    onError(error: any): void;
    onFormError(err: any): void;
    setContext(route: ActivatedRoute): void;
    loadForm(): any;
    loadParents(): any;
    onSubmissionError(err: any): void;
    loadResource(route: ActivatedRoute): any;
    save(resource: any): Promise<any>;
    remove(): Promise<void>;
    static ɵfac: i0.ɵɵFactoryDef<FormioResourceService, [null, null, { optional: true; }, null]>;
    static ɵprov: i0.ɵɵInjectableDef<FormioResourceService>;
}
//# sourceMappingURL=resource.service.d.ts.map